### ISSUE TITLE
FR: Verbose Error Output

### ISSUE THREAD

**Issue by a-marionette** [wagiro/BurpBounty#103]
Hello,

It would be helpful to have more verbose error output (including the BB profile which invoked the error). For example, I am unable to determine what is causing the error on Line 3 of the error console.

![Screen Shot 2021-03-16 at 12 44 50 AM](https://user-images.githubusercontent.com/16928471/111273253-d3621d80-85f0-11eb-9a84-70f2a25c3aab.png)

**Comment by wagiro** [comment]
Hi @a-marionette !

Wow what a FR hehehe, this code is currently obsolete because the Burp Bounty Pro and the future Burp Bounty Community have a much more optimal code and many more functionalities. In one or two months I will publish them.

You can see more information at:

https://burpbounty.net

Thanks!
Best regards.
