### ISSUE TITLE
Scan specific parameter

### ISSUE THREAD

**Issue by root711** [wagiro/BurpBounty#28]
Is the option to scan a specific parameter there?
for example

```
GET /bWAPP/sqli_4.php?title=x-men&action=search HTTP/1.1
Host: itsecgames.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://itsecgames.com/bWAPP/sqli_4.php
DNT: 1
Connection: close
Cookie: PHPSESSID=ca30748e7e3c43d1d7d0ceaa1f463eb9; security_level=0
Upgrade-Insecure-Requests: 1
```

Scanning title for SQL?

**Comment by wagiro** [comment]
Hi @root711 !

Not, because the extension is designed for scans generically, not for a specific request. What you tell me you can do with the burp intruder.

What I do plan to implement is that you can select the type of insertion point to scan, file path, url parameter, directory path, etc.

Regards!
