### ISSUE TITLE
Support for BurpPro v2.1.07?

### ISSUE THREAD

**Issue by michael-barone** [wagiro/BurpBounty#47]
Passive audit check "hangs" and does not complete. Started noticing this issue around v2.1.04-v2.1.05 of BurpSuite Professional. Tried 3.0.5 and 3.0.6beta of BurpBounty and same issue. 

No errors in the extension output. It seems to get stuck while scanning a favicon.ico page. Maybe something with unsupported characters?

Thanks!

**Comment by wagiro** [comment]
Hi @michael-barone !

Thanks for the issue, the extension had a problem and sometimes when you added a payload with \r it was saved. Then it was consuming a lot of cpu because it made the request GET /some/path.php?var=payload\r HTTP/1.1

I am solving all issues and I will soon release version 3.1.

Best regards.
