### ISSUE TITLE
3.4 not working in Burp Pro v2020.7

### ISSUE THREAD

**Issue by ttymeh** [wagiro/BurpBounty#69]
When installing, i get this error over and over again:

```
java.lang.NullPointerException
	at burp.axk.analyzeRequest(Unknown Source)
	at burp.ee3.analyzeRequest(Unknown Source)
	at burpbounty.BurpBountyExtension.getInsertionPoints(BurpBountyExtension.java:129)
	at burp.dt5.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

no other extensions loaded.

**Comment by jhaddix** [comment]
Hey @wagiro , I am also receiving the same error above.  Could use some help.

**Comment by wagiro** [comment]
Hi @jhaddix @ttymeh ! 

Yes, this error happens to few people and I have not been able to isolate because happen. The line BurpBountyExtension.java:129 is in the function:

```
@Override
    public List<IScannerInsertionPoint> getInsertionPoints(IHttpRequestResponse baseRequestResponse) {
        List<IScannerInsertionPoint> insertionPoints = new ArrayList();

        try{
Line 129->   IRequestInfo request = helpers.analyzeRequest(baseRequestResponse);

            if (request.getMethod().equals("GET")) {
                .....
            }
        }catch (NullPointerException e){
            return insertionPoints;
        }
        return insertionPoints;
    }

```


As you can see, I try to fix it with a big Try/Catch for non NullPointerException returned...but not is the solution.

I would need to connect to a remote machine through teamviewer or similar to debug the extension in-place, since I can't reproduce that error on my machine.

I think I know someone who happens to him, I will ask him to let me connect to see the root cause and be able to solve it

Thans for the issue!

**Comment by jhaddix** [comment]
I figured it out (for me at least). 

Turns out the path that Burp was attempting to retrieve the .bb templates from was a protected path (C:/Program\ Files) in Windows (needs admin to write/read). I simply specified a new folder for the templates on my desktop and it started working! 

Sorry for the alarm!

**Comment by ChrisPritchard** [comment]
> I figured it out (for me at least).
> 
> Turns out the path that Burp was attempting to retrieve the .bb templates from was a protected path (C:/Program\ Files) in Windows (needs admin to write/read). I simply specified a new folder for the templates on my desktop and it started working!
> 
> Sorry for the alarm!

this was the issue for me too. thanks champ!

**Comment by wagiro** [comment]
Solved, I was changed the default directory from user.dir to user.home.

Thanks to all!
