### ISSUE TITLE
Active profile, don't understand how payload works

### ISSUE THREAD

**Issue by Kiblyn11** [wagiro/BurpBounty#71]
Hello,

I really like your project but have some issues with active profiles.

I'm trying to build a simple active profile which add a header and match string on response.
But I can't figure out how the payload works.
I've added my new header in payload and selected "Append" or "Replace", "Header"
![image](https://user-images.githubusercontent.com/4669951/90618499-63351a00-e210-11ea-9bee-e83d5c5ce713.png)

But when i check in logger++ I see that it didn't add a new header, it append to Referrer header.

![image](https://user-images.githubusercontent.com/4669951/90618678-9ecfe400-e210-11ea-8dd6-fa28230d3852.png)

I tried to check doc, but couldn't find anything about it.
Also if I check other templates such as WebCachePoisonning, it doesn't really make sense to me because everything is checked, and in logger++ I see incoherent request.

**Comment by wagiro** [comment]
Hi Kiblyn11!

Thanks for the issue. The free version of Burp Bounty has some bugs that will be fixed in the next version.

For now, to do what you say, try:

![cache](https://user-images.githubusercontent.com/3398430/90619975-2cf89a00-e212-11ea-9b57-46cb7e073088.png)

![cache2](https://user-images.githubusercontent.com/3398430/90619986-31bd4e00-e212-11ea-8c75-1241af515f4a.png)

And search in response something.

As you can see in logger++ the request add new header:

![cache3](https://user-images.githubusercontent.com/3398430/90620039-426dc400-e212-11ea-946a-8da3106282ca.png)


Best regards!

PD: Soon Burp Bounty Pro, a very improved version of Burp Bounty, with a profesional profiles pack and intelligent automatic scanner integrated, all for 59€/year :D

**Comment by Kiblyn11** [comment]
Thanks @wagiro for quick response.
I wasn't aware of Pro version of Burp Bounty coming. Eager to see that !

**Comment by wagiro** [comment]
Does it work well for you?

Yes! Burp Bounty Pro, here you can see an old example, now it is much more powerful!

* https://drive.google.com/file/d/1eI-EWBWes16vpy1zhUntFi41-cAGPmel/view?usp=sharing

Stay informed on twitter:

* https://twitter.com/BurpBounty

**Comment by Kiblyn11** [comment]
Nice.
Yes it's working as expected ! Thanks.
